server:
  port: 8093
  servlet:
    context-path: /

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
  security:
    oauth2:
      client:
        registration:
          blog-client:
            client-id: blog-client
            client-secret: blog-secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/blog-client"
            scope: blog.read
        provider:
          blog-client:
            authorization-uri: http://localhost:8096/oauth2/authorize
            token-uri: http://localhost:8096/oauth2/token
            user-info-uri: http://localhost:8096/userinfo
            user-name-attribute: sub
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8096/oauth2/jwks